/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Button;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import models.CPU;
import models.Memory;
import models.Program;

/**
 *
 * @author Usuario
 */
public class Window extends javax.swing.JFrame {

  /**
   * Creates new form Window
   */
  File file;
  DefaultTableModel modelo;
  boolean flag = false;
  Program program;
  CPU cpu;
  int instIndex = 0;

  public Window() {

    initComponents();
    jButtonSizeMemory.setEnabled(flag);
    Button executeButton = new Button();
    executeButton.setEnabled(false);
  }
//

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    textArea = new java.awt.TextArea();
    jTextFieldFile = new javax.swing.JTextField();
    jButtonLoad = new javax.swing.JButton();
    jButtonClear = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    executeButton = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jPanel6 = new javax.swing.JPanel();
    jTextFieldSizeMemory = new javax.swing.JTextField();
    jButtonSizeMemory = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jPanel3 = new javax.swing.JPanel();
    jPanel4 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jTextFieldAX = new javax.swing.JTextField();
    jTextFieldBX = new javax.swing.JTextField();
    jTextFieldCX = new javax.swing.JTextField();
    jTextFieldDX = new javax.swing.JTextField();
    jPanel5 = new javax.swing.JPanel();
    jTextFieldPC = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jTextFieldIR = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jTextFieldAC = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("File"));
    jPanel1.setName("LoadFile"); // NOI18N

    jButton1.setText("File");
    jButton1.setBorder(null);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    textArea.setEditable(false);
    textArea.setName("txtArea"); // NOI18N

    jTextFieldFile.setEditable(false);

    jButtonLoad.setText("Load");
    jButtonLoad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonLoadActionPerformed(evt);
      }
    });

    jButtonClear.setText("Clear");
    jButtonClear.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonClearActionPerformed(evt);
      }
    });

    jLabel1.setText("Content");

    executeButton.setText("Execute Next");
    executeButton.setEnabled(false);
    executeButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        executeButtonMouseClicked(evt);
      }
    });
    executeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        executeButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                  .addComponent(jTextFieldFile, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGap(18, 18, 18))
                .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(76, 76, 76)
            .addComponent(executeButton)))
        .addContainerGap(24, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(54, 54, 54)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1)
          .addComponent(jTextFieldFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButtonLoad)
          .addComponent(jButtonClear))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel1)
        .addGap(2, 2, 2)
        .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(executeButton)
        .addContainerGap())
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Memory"));

    jButtonSizeMemory.setText("Set Memory Size");
    jButtonSizeMemory.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButtonSizeMemoryMouseClicked(evt);
      }
    });
    jButtonSizeMemory.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonSizeMemoryActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTextFieldSizeMemory)
        .addGap(18, 18, 18)
        .addComponent(jButtonSizeMemory)
        .addGap(8, 8, 8))
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextFieldSizeMemory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButtonSizeMemory))
        .addContainerGap(19, Short.MAX_VALUE))
    );

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null}
      },
      new String [] {
        "Space", "Bin Instructions "
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jTable1.setRowHeight(10);
    jScrollPane1.setViewportView(jTable1);
    if (jTable1.getColumnModel().getColumnCount() > 0) {
      jTable1.getColumnModel().getColumn(0).setMinWidth(60);
      jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
      jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
    }

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(27, Short.MAX_VALUE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Registers"));
    jPanel3.setName(""); // NOI18N

    jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jLabel5.setText("AX");

    jLabel6.setText("BX");

    jLabel7.setText("CX");

    jLabel8.setText("DX");

    jTextFieldAX.setEditable(false);

    jTextFieldBX.setEditable(false);

    jTextFieldCX.setEditable(false);

    jTextFieldDX.setEditable(false);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel4Layout.createSequentialGroup()
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jTextFieldAX))
          .addGroup(jPanel4Layout.createSequentialGroup()
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jTextFieldDX))
          .addGroup(jPanel4Layout.createSequentialGroup()
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jTextFieldBX))
          .addGroup(jPanel4Layout.createSequentialGroup()
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jTextFieldCX)))
        .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGap(11, 11, 11)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(jTextFieldAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(jTextFieldBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(10, 10, 10)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(jTextFieldCX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextFieldDX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jTextFieldPC.setEditable(false);

    jLabel2.setText("PC");

    jTextFieldIR.setEditable(false);

    jLabel3.setText("IR");

    jTextFieldAC.setEditable(false);

    jLabel4.setText("AC");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextFieldPC, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addGroup(jPanel5Layout.createSequentialGroup()
              .addComponent(jLabel4)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(jTextFieldAC, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
              .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(jTextFieldIR))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addGap(16, 16, 16)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextFieldPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addGap(18, 18, 18)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jTextFieldIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextFieldAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addGap(0, 9, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(43, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(9, 9, 9)
        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(41, 41, 41)
        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(103, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:
      JFileChooser fc = new JFileChooser();

      FileNameExtensionFilter filter = new FileNameExtensionFilter(".asm", "asm");

      fc.setFileFilter(filter);

      //fc.showOpenDialog(null);
      int result = fc.showSaveDialog(this);
      if (result == JFileChooser.APPROVE_OPTION) {
        file = fc.getSelectedFile();
        String nameFile = file.getName();
        jTextFieldFile.setText(nameFile);
        flag = true;
      } else {
        JOptionPane.showMessageDialog(null, "CHOOSE A FILE.");
        flag = false;
      }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadActionPerformed
      // TODO add your handling code here:

      if (flag == true) {
        jButtonSizeMemory.setEnabled(flag);
        try {
          FileReader fr = new FileReader(file);
          BufferedReader br = new BufferedReader(fr);
          String text = "";
          String line = "";
          ArrayList<String[]> instructionsParser = new ArrayList<>();
          int lineNumber = 0;
          int errCount = 0;
          while (((line = br.readLine()) != null)) {
            String lineFormat = line;
            if (line.contains(",")) {
              instructionsParser.add(line.replace(",", "").split(" "));
            } else {
              String newLine = line + ", x";
              instructionsParser.add(newLine.replace(",", "").split(" "));
            }
            if (instructionFormatter(lineFormat)) {
              text += line + "\n";
            } else {
              JOptionPane.showMessageDialog(null, "SYNTAX ERR AT LINE " + lineNumber + ". STOPPING PROCESS.");
              errCount += 1;
            }
            lineNumber++;
          }

          int instructionsQuantity = instructionsParser.size();
          String[] programInstructions = new String[3 * instructionsQuantity];
          int i = 0;
          for (String[] val : instructionsParser) {
            for (String inst : val) {
              programInstructions[i] = inst;
              i += 1;
            }
          }

          if (errCount > 0) {
            text = "FIX THE ERROS AND LOAD THE PROGRAM AGAIN.";
          }
          this.program = new Program(instructionsQuantity, programInstructions);
          textArea.setText(text);

        } catch (FileNotFoundException ex) {
          Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
          Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
      } else {
        JOptionPane.showMessageDialog(null, "LOAD A FILE FIRST.");
      }

    }//GEN-LAST:event_jButtonLoadActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
      // TODO add your handling code here:
      jButtonSizeMemory.setEnabled(false);
      executeButton.setEnabled(false);
      textArea.setText("");
      modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int filas, int columnas) {
          if (columnas == 2) {
            return true;

          } else {
            return false;
          }
        }
      };
      modelo.addColumn("Space");
      modelo.addColumn("Bin Instructions");

      jTable1.setModel(modelo);
      jTable1.getColumnModel().getColumn(0).setMinWidth(60);
      jTable1.getColumnModel().getColumn(0).setMaxWidth(60);

      jTextFieldAC.setText("");
      jTextFieldIR.setText("");
      jTextFieldPC.setText("");
      jTextFieldAX.setText("");
      jTextFieldBX.setText("");
      jTextFieldCX.setText("");
      jTextFieldDX.setText("");
      jTextFieldSizeMemory.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonSizeMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSizeMemoryActionPerformed
      // TODO add your handling code here:

      if (jTextFieldSizeMemory.getText().isBlank()) {
        JOptionPane.showMessageDialog(null, "SET THE MEMORY SIZE FIRST.");
      } else {
        String memory = jTextFieldSizeMemory.getText();
        boolean isNumeric = memory.matches("[+]?\\d*(\\.\\d+)?");

        modelo = new DefaultTableModel() {
          @Override
          public boolean isCellEditable(int filas, int columnas) {
            if (columnas == 2) {
              return true;

            } else {
              return false;
            }
          }
        };
        modelo.addColumn("Space");
        modelo.addColumn("Bin Instructions");

        jTable1.setModel(modelo);
        jTable1.getColumnModel().getColumn(0).setMinWidth(60);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
        if (isNumeric) {
          int num = Integer.valueOf(memory);

          for (int i = 0; i < num; i++) {
            modelo.setNumRows(num);
            jTable1.setValueAt(i, i, 0);

          }

        }

      }
      executeButton.setEnabled(true);
      //if (jTextFieldSizeMemory.getText() != "") {

      //}

    }//GEN-LAST:event_jButtonSizeMemoryActionPerformed

  private void jButtonSizeMemoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSizeMemoryMouseClicked
    // TODO add your handling code here:
    // TODO add your handling code here:
    int memSize = Integer.parseInt(jTextFieldSizeMemory.getText());

    Memory memory = new Memory(memSize);

    if (memory.mountProgram(program)) {
      this.cpu = new CPU(memory);
      this.instIndex = cpu.getMemory().getProgramIndex();
      String[] instructions = cpu.getMemory().getStack();
      int programPos = cpu.getMemory().getProgramIndex() - 1;
      for (int i = programPos; i < memSize; i++) {
        jTable1.setValueAt(instructions[i], i, 1);
      }
    } else {
      JOptionPane.showMessageDialog(null, "THERE IS NOT ENOUGH MEMORY FOR THE PROGRAM.");
    }

  }//GEN-LAST:event_jButtonSizeMemoryMouseClicked

  private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_executeButtonActionPerformed

  private void executeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_executeButtonMouseClicked
    // TODO add your handling code here:
    DefaultTableCellRenderer columnRender = new DefaultTableCellRenderer();
    TableModel model = jTable1.getModel();

    cpu.executeProgram(this.instIndex);
    updateRegisters();
    this.instIndex += 1;
  }//GEN-LAST:event_executeButtonMouseClicked

  private void updateRegisters() {

    jTextFieldPC.setText(String.valueOf(cpu.getRegister("PC").getCurrentValue()));
    jTextFieldAC.setText(String.valueOf(cpu.getRegister("AC").getCurrentValue()));
    jTextFieldIR.setText(String.valueOf(cpu.getRegister("IR").getCurrentValue()));

    jTextFieldAX.setText(String.valueOf(cpu.getRegister("0001").getCurrentValue()));
    jTextFieldBX.setText(String.valueOf(cpu.getRegister("0010").getCurrentValue()));
    jTextFieldCX.setText(String.valueOf(cpu.getRegister("0011").getCurrentValue()));
    jTextFieldDX.setText(String.valueOf(cpu.getRegister("0100").getCurrentValue()));

  }

  private boolean instructionFormatter(String instruction) {

    String[] instr;
    if (instruction.contains(",")) {
      instr = instruction.replace(",", "").split(" ");
    } else {
      String newLine = instruction + ", x";
      instr = newLine.replace(",", "").split(" ");
    }

    if (instr[0].contentEquals("MOV") || instr[0].contentEquals("LOAD") || instr[0].contentEquals("STORE") || instr[0].contentEquals("ADD") || instr[0].contentEquals("SUB")) {
      if (instr[1].contentEquals("AX") || instr[1].contentEquals("BX") || instr[1].contentEquals("CX") || instr[1].contentEquals("DX")) {
        if (instr[2].contentEquals("x") || (instr[2].matches("-?\\d+(\\.\\d+)?"))) {
          return true;
        } else {
          return false;
        }
      } else {
        return false;
      }
    } else {
      return false;
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;

        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Window.class
              .getName()).log(java.util.logging.Level.SEVERE, null, ex);

    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Window.class
              .getName()).log(java.util.logging.Level.SEVERE, null, ex);

    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Window.class
              .getName()).log(java.util.logging.Level.SEVERE, null, ex);

    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Window.class
              .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Window().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton executeButton;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButtonClear;
  private javax.swing.JButton jButtonLoad;
  private javax.swing.JButton jButtonSizeMemory;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JTextField jTextFieldAC;
  private javax.swing.JTextField jTextFieldAX;
  private javax.swing.JTextField jTextFieldBX;
  private javax.swing.JTextField jTextFieldCX;
  private javax.swing.JTextField jTextFieldDX;
  private javax.swing.JTextField jTextFieldFile;
  private javax.swing.JTextField jTextFieldIR;
  private javax.swing.JTextField jTextFieldPC;
  private javax.swing.JTextField jTextFieldSizeMemory;
  private java.awt.TextArea textArea;
  // End of variables declaration//GEN-END:variables
}
